server {
    listen 80;
    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream_frontend front-end:9000;
        proxy_pass http://$upstream_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        set $upstream_backend back-end:5252;
        proxy_pass http://$upstream_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
